import type { Metadata } from "next";
import Link from "next/link";
import { Filter, Search } from "lucide-react";
import { OpportunityCard } from "@/components/opportunity-card";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { Button } from "@/components/ui/button";
import { featuredOpportunities } from "@/lib/constants";

export const metadata: Metadata = { title: "Opportunities" };
const filters = ["All", "Scholarships", "Jobs", "Internships", "Programs", "Remote"];
export default function OpportunitiesPage() { const opportunities = [...featuredOpportunities, { id: "climate-fellows", title: "Africa Climate Fellows Program", organization: "Green Horizons", type: "Program" as const, location: "Africa · Hybrid", deadline: "2026-09-02", tags: ["Climate", "Fellowship"] }, { id: "growth-remote", title: "Growth Marketing Associate", organization: "Grow Something Good", type: "Job" as const, location: "Remote · Worldwide", deadline: "2026-08-29", tags: ["Marketing", "Remote"] }, { id: "research-grant", title: "Open Research Grant", organization: "Knowledge Commons", type: "Scholarship" as const, location: "Worldwide", deadline: "2026-10-01", tags: ["Research", "Funding"] }]; return <><SiteHeader /><main><PageHero eyebrow="Curated for you" title={<>Find the door that opens your <span className="text-gradient">next chapter.</span></>} description="Real scholarships, jobs, internships, and programs. Saved time means more energy for applying." /><section className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="flex flex-col gap-4 border-b border-slate-200 pb-6 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-2 overflow-x-auto pb-1">{filters.map((filter, index) => <Link href={index ? `/opportunities?type=${filter}` : "/opportunities"} key={filter} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${index === 0 ? "bg-slate-950 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{filter}</Link>)}</div><div className="flex gap-2"><Button variant="outline" size="sm"><Filter className="size-4" />Filters</Button><Button variant="outline" size="sm" asChild><Link href="/search"><Search className="size-4" />Search</Link></Button></div></div><p className="mt-7 text-sm text-slate-500"><strong className="text-slate-800">{opportunities.length} opportunities</strong> selected for the Allinonehub community</p><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{opportunities.map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} />)}</div><div className="mt-12 rounded-3xl bg-slate-50 p-8 text-center"><p className="font-bold text-slate-950">Know an opportunity worth sharing?</p><p className="mt-2 text-sm text-slate-600">Help someone else take their next step.</p><Button variant="outline" className="mt-5" asChild><Link href="/dashboard/submit-opportunity">Submit an opportunity</Link></Button></div></section></main><SiteFooter /></>; }
