import Link from "next/link";
import { ArrowLeft, Bookmark, CalendarDays, CheckCircle2, ExternalLink, MapPin, Share2 } from "lucide-react";
import { notFound } from "next/navigation";
import { featuredOpportunities } from "@/lib/constants";
import { formatDate } from "@/lib/utils";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default async function OpportunityDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const opportunity = featuredOpportunities.find((item) => item.id === slug); if (!opportunity) notFound(); return <><SiteHeader /><main className="bg-slate-50"><div className="mx-auto max-w-5xl px-5 py-8 lg:px-8"><Link href="/opportunities" className="inline-flex items-center gap-1 text-sm font-bold text-slate-600 hover:text-blue-600"><ArrowLeft className="size-4" />All opportunities</Link><article className="mt-6 grid gap-8 lg:grid-cols-[1fr_300px]"><div className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-10"><Badge className="bg-violet-100 text-violet-700">{opportunity.type}</Badge><h1 className="mt-5 text-3xl font-black tracking-[-.04em] text-slate-950 sm:text-5xl">{opportunity.title}</h1><p className="mt-3 text-lg text-slate-600">{opportunity.organization}</p><div className="mt-8 grid gap-4 border-y border-slate-100 py-6 sm:grid-cols-2"><Info icon={MapPin} label="Location" value={opportunity.location} /><Info icon={CalendarDays} label="Application deadline" value={formatDate(opportunity.deadline)} /></div><div className="mt-8"><h2 className="text-xl font-black text-slate-950">About this opportunity</h2><p className="mt-3 leading-7 text-slate-600">This opportunity is selected for people in the Allinonehub community. Check the official application page for complete eligibility rules, documentation, and the latest updates before applying.</p><h2 className="mt-8 text-xl font-black text-slate-950">Before you apply</h2><ul className="mt-4 space-y-3 text-slate-600">{["Read every eligibility requirement carefully.", "Prepare your CV, personal statement, and requested documents.", "Apply before the deadline and save your confirmation."].map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-500" />{item}</li>)}</ul></div></div><aside className="h-fit rounded-3xl border border-slate-200 bg-white p-5"><Button variant="primary" size="lg" className="w-full" asChild><a href="#apply">Visit application <ExternalLink className="size-4" /></a></Button><Button variant="outline" className="mt-3 w-full"><Bookmark className="size-4" />Save for later</Button><Button variant="ghost" className="mt-2 w-full"><Share2 className="size-4" />Share</Button><p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Always apply through official links. Never send money to apply for an opportunity listed here.</p></aside></article></div></main><SiteFooter /></>; }
function Info({ icon: Icon, label, value }: { icon: typeof MapPin; label: string; value: string }) { return <div className="flex gap-3"><Icon className="mt-0.5 size-5 text-blue-600" /><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div></div>; }
