import Link from "next/link";
import { ArrowRight, BookOpen, ChevronRight, CirclePlay, Globe2, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { HomeHero } from "@/components/home-hero";
import { NewsletterForm } from "@/components/newsletter-form";
import { OpportunityCard } from "@/components/opportunity-card";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { categories, featuredOpportunities, learningPaths } from "@/lib/constants";

export default function Home() {
  return <><SiteHeader /><main>
    <HomeHero />
    <section className="border-y border-slate-100 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-slate-100 px-5 sm:grid-cols-4 sm:divide-y-0 lg:px-8"><Stat value="30k+" label="people building forward" /><Stat value="1,200+" label="curated opportunities" /><Stat value="28" label="countries represented" /><Stat value="100%" label="free to get started" /></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-2xl"><Badge className="bg-blue-50 text-blue-700">Everything you need, connected</Badge><h2 className="mt-4 text-3xl font-black tracking-[-.04em] text-slate-950 sm:text-4xl">One place to explore what is possible.</h2><p className="mt-4 leading-7 text-slate-600">No more scattered links, missed deadlines, or learning alone. Allinonehub brings the next step closer.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.slice(0, 6).map((category) => { const Icon = category.icon; return <Link href={`/search?category=${category.name.toLowerCase()}`} key={category.name} className="group rounded-2xl border border-slate-200 bg-white p-5 transition-all hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-950/5"><div className={`grid size-11 place-items-center rounded-xl ${category.color}`}><Icon className="size-5" /></div><h3 className="mt-5 font-bold tracking-tight text-slate-950">{category.name}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{category.description}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-blue-600">Explore <ChevronRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link>; })}</div></section>
    <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><Badge className="bg-violet-100 text-violet-700"><Sparkles className="mr-1 size-3.5" />Freshly curated</Badge><h2 className="mt-4 text-3xl font-black tracking-[-.04em] text-slate-950 sm:text-4xl">Worth your attention.</h2><p className="mt-3 max-w-xl text-slate-600">Real openings selected to help you learn, work, and make an impact.</p></div><Button variant="outline" asChild><Link href="/opportunities">See all opportunities <ArrowRight className="size-4" /></Link></Button></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{featuredOpportunities.map((opportunity) => <OpportunityCard opportunity={opportunity} key={opportunity.id} />)}</div></div></section>
    <section className="overflow-hidden bg-slate-950"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 text-white lg:grid-cols-[.85fr_1.15fr] lg:px-8 lg:py-28"><div><Badge className="bg-white/10 text-blue-200"><BookOpen className="mr-1 size-3.5" />Learn in a way that sticks</Badge><h2 className="mt-5 text-4xl font-black tracking-[-.045em] sm:text-5xl">Practical knowledge for the life you want.</h2><p className="mt-5 max-w-md leading-7 text-slate-300">Follow friendly, focused paths built around the decisions you are making right now.</p><Button className="mt-8 bg-white text-slate-950 hover:bg-slate-100" size="lg" asChild><Link href="/learn">Explore learning <ArrowRight className="size-4" /></Link></Button></div><div className="grid gap-4">{learningPaths.map((path, index) => { const Icon = path.icon; return <Link key={path.title} href="/learn" className="group flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-4 transition hover:border-white/30 hover:bg-white/10 sm:p-5"><div className={`grid size-12 shrink-0 place-items-center rounded-xl bg-gradient-to-br ${path.accent} text-white`}><Icon className="size-5" /></div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Path {String(index + 1).padStart(2, "0")} · {path.lessons} lessons</p><h3 className="mt-1 font-bold text-white">{path.title}</h3></div><CirclePlay className="size-5 shrink-0 text-slate-400 transition group-hover:text-white" /></Link>; })}<div className="mt-2 flex items-center gap-3 px-2 text-sm text-slate-400"><span className="grid size-8 place-items-center rounded-full bg-emerald-500/20 text-emerald-300">✓</span>Learn at your pace. Come back anytime.</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid overflow-hidden rounded-[2rem] bg-[#eef4ff] lg:grid-cols-[1.05fr_.95fr]"><div className="p-8 sm:p-12"><Badge className="bg-white text-blue-700"><UsersRound className="mr-1 size-3.5" />Built around people</Badge><h2 className="mt-5 text-3xl font-black tracking-[-.04em] text-slate-950 sm:text-4xl">A community that sees your potential.</h2><p className="mt-5 max-w-lg leading-7 text-slate-600">Ask a question, share your progress, or find a collaborator. Here, generosity is a feature — not an afterthought.</p><Button variant="primary" className="mt-8" size="lg" asChild><Link href="/community">Meet the community <ArrowRight className="size-4" /></Link></Button></div><div className="relative min-h-72 p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(147,197,253,.75),transparent_65%)]" /><div className="relative mx-auto max-w-sm space-y-3"><CommunityNote name="Aline M." tag="Kigali, Rwanda" text="I found a mentor here who helped me turn an idea into my first real portfolio." color="bg-white" /><CommunityNote name="Samuel K." tag="Nairobi, Kenya" text="The scholarship checklist saved me hours. I’m finally applying with confidence." color="ml-8 bg-blue-600 text-white" inverse /><CommunityNote name="Nadia H." tag="Remote · Morocco" text="A space that makes learning feel less lonely." color="bg-white" /></div></div></div></section>
    <section className="bg-blue-600 px-5 py-20 text-center text-white sm:py-24"><ShieldCheck className="mx-auto size-8 text-blue-200" /><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-black tracking-[-.04em] sm:text-4xl">Your future deserves a place to grow.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-blue-100">Join a growing network of learners, builders, and dreamers. It costs nothing to begin.</p><Button className="mt-8 bg-white text-blue-700 hover:bg-blue-50" size="lg" asChild><Link href="/auth/sign-up">Create your free account <ArrowRight className="size-4" /></Link></Button></section>
    <section className="bg-slate-950 px-5 py-20 text-center text-white sm:py-24"><Globe2 className="mx-auto size-7 text-blue-300" /><h2 className="mt-5 text-2xl font-black tracking-tight sm:text-3xl">A small note from us, whenever it matters.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-300">Weekly opportunities, useful resources, and stories from the community. No noise.</p><div className="mt-7"><NewsletterForm dark /></div></section>
  </main><SiteFooter /></>;
}

function Stat({ value, label }: { value: string; label: string }) { return <div className="px-3 py-7 text-center sm:py-8"><p className="text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">{value}</p><p className="mt-1 text-xs font-medium text-slate-500 sm:text-sm">{label}</p></div>; }
function CommunityNote({ name, tag, text, color, inverse = false }: { name: string; tag: string; text: string; color: string; inverse?: boolean }) { return <div className={`rounded-2xl p-4 shadow-xl shadow-blue-950/5 ${color}`}><div className="flex items-center gap-3"><span className={`grid size-9 place-items-center rounded-full text-xs font-bold ${inverse ? "bg-white/20 text-white" : "bg-blue-100 text-blue-700"}`}>{name.split(" ").map((part) => part[0]).join("")}</span><div><p className={`text-sm font-bold ${inverse ? "text-white" : "text-slate-900"}`}>{name}</p><p className={`text-xs ${inverse ? "text-blue-100" : "text-slate-500"}`}>{tag}</p></div></div><p className={`mt-3 text-sm leading-6 ${inverse ? "text-white" : "text-slate-600"}`}>“{text}”</p></div>; }
