"use client";

import { FormEvent, useState } from "react";
import { ArrowUp, Bot, Loader2, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

type Message = { role: "user" | "assistant"; content: string };
const prompts = ["How do I find scholarships that fit me?", "Help me plan a tech career", "What should I put in my first CV?", "Recommend free courses for marketing"];

export function AssistantChat() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Hi — I’m your Allinone guide. Tell me what you are working toward, and I’ll help you decide on a useful next step." }]);
  const [input, setInput] = useState(""); const [loading, setLoading] = useState(false);
  async function send(event?: FormEvent, prompt?: string) { event?.preventDefault(); const content = (prompt ?? input).trim(); if (!content || loading) return; const next = [...messages, { role: "user" as const, content }]; setMessages(next); setInput(""); setLoading(true); try { const response = await fetch("/api/assistant", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "The assistant is unavailable."); setMessages((current) => [...current, { role: "assistant", content: payload.message }]); } catch (error) { setMessages((current) => [...current, { role: "assistant", content: error instanceof Error ? error.message : "I couldn’t respond just now. Please try again." }]); } finally { setLoading(false); } }
  return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-900/5"><div className="flex items-center gap-3 border-b border-slate-100 bg-slate-50 p-4"><span className="grid size-10 place-items-center rounded-2xl bg-blue-600 text-white"><Sparkles className="size-5" /></span><div><p className="font-black text-slate-950">Allinone guide</p><p className="text-xs text-emerald-600">● Ready to help</p></div></div><div className="min-h-[400px] space-y-5 p-5 sm:p-6">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={cn("flex gap-3", message.role === "user" && "justify-end")}><span className={cn("grid size-8 shrink-0 place-items-center rounded-full text-xs font-bold", message.role === "assistant" ? "bg-blue-100 text-blue-700" : "order-2 bg-slate-950 text-white")}>{message.role === "assistant" ? <Bot className="size-4" /> : "YU"}</span><p className={cn("max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-6", message.role === "assistant" ? "rounded-tl-sm bg-slate-100 text-slate-700" : "rounded-tr-sm bg-blue-600 text-white")}>{message.content}</p></div>)}{loading && <div className="flex gap-3"><span className="grid size-8 place-items-center rounded-full bg-blue-100 text-blue-700"><Bot className="size-4" /></span><div className="rounded-2xl rounded-tl-sm bg-slate-100 px-4 py-3"><Loader2 className="size-4 animate-spin text-blue-600" /></div></div>}</div>{messages.length === 1 && <div className="flex flex-wrap gap-2 px-5 pb-4">{prompts.map((prompt) => <button onClick={() => send(undefined, prompt)} key={prompt} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700">{prompt}</button>)}</div>}<form onSubmit={send} className="border-t border-slate-100 p-3"><div className="flex items-center gap-2 rounded-2xl bg-slate-100 p-1.5"><label className="sr-only" htmlFor="assistant-message">Ask anything</label><input id="assistant-message" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about learning, careers, or opportunities..." className="h-10 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-slate-400" /><button disabled={!input.trim() || loading} aria-label="Send message" className="grid size-10 place-items-center rounded-xl bg-slate-950 text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-40"><ArrowUp className="size-4" /></button></div></form></div>;
}
