"use client";

import Link from "next/link";
import { Search, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { featuredOpportunities } from "@/lib/constants";
import { OpportunityCard } from "@/components/opportunity-card";

const results = [...featuredOpportunities, { id: "writing-guide", title: "How to write a scholarship personal statement", organization: "Allinonehub Learning", type: "Program" as const, location: "Learning resource", deadline: "2027-01-01", tags: ["Scholarships", "Writing"] }, { id: "community-tech", title: "Tech learners community", organization: "Allinonehub Community", type: "Program" as const, location: "Online", deadline: "2027-01-01", tags: ["Technology", "Community"] }];
export function SearchExperience() { const params = useSearchParams(); const [query, setQuery] = useState(params.get("q") ?? ""); const matched = useMemo(() => results.filter((item) => `${item.title} ${item.organization} ${item.type} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query]); return <><div className="relative mx-auto max-w-3xl"><Search className="absolute left-5 top-1/2 size-5 -translate-y-1/2 text-slate-400" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search opportunities, guides, communities..." className="h-16 w-full rounded-2xl border border-slate-200 bg-white pl-14 pr-12 text-base shadow-lg shadow-slate-900/5 outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100" />{query && <button onClick={() => setQuery("")} className="absolute right-4 top-1/2 -translate-y-1/2 rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="size-4" /></button>}</div><p className="mt-8 text-sm text-slate-500">{query ? <><strong className="text-slate-800">{matched.length}</strong> results for “{query}”</> : "Start typing or browse a suggested topic."}</p>{query ? <div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{matched.map((item) => <OpportunityCard key={item.id} opportunity={item} />)}</div> : <div className="mt-5 flex flex-wrap gap-2">{["Scholarships", "Remote jobs", "Technology", "Free courses", "Community"].map((topic) => <button onClick={() => setQuery(topic)} key={topic} className="rounded-full bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-blue-50 hover:text-blue-700">{topic}</button>)}</div>}{query && !matched.length && <div className="mt-5 rounded-2xl border border-dashed border-slate-300 p-10 text-center"><p className="font-bold text-slate-800">No exact match yet.</p><p className="mt-2 text-sm text-slate-500">Try a broader term, or ask the community.</p><Link href="/community" className="mt-4 inline-block text-sm font-bold text-blue-600">Ask the community →</Link></div>}</>; }
