import { Bell, LockKeyhole, UserRound } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";
import { ProfileSettingsForm } from "@/components/profile-settings-form";
import { PushNotificationButton } from "@/components/push-notification-button";

export default async function SettingsPage() {
  const user = await getCurrentUser();
  return <div className="mx-auto max-w-3xl"><p className="text-sm font-semibold text-blue-600">YOUR ACCOUNT</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em] text-slate-950">Settings</h1><p className="mt-2 text-slate-600">Keep your profile useful, private, and truly yours.</p><div className="mt-8 grid gap-6"><section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><UserRound className="size-5" /></span><div><h2 className="font-black text-slate-950">Public profile</h2><p className="text-sm text-slate-500">Control how the community sees you.</p></div></div><div className="mt-7"><ProfileSettingsForm profile={{ fullName: user?.fullName ?? "", bio: "", location: "", interests: [] }} /></div></section><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><Bell className="size-5" /></span><div><h2 className="font-black text-slate-950">Notifications</h2><p className="mt-1 text-sm leading-6 text-slate-600">We only send useful updates: saved deadline reminders, messages, and new opportunities that match your interests.</p><PushNotificationButton /></div></div></section><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><LockKeyhole className="size-5" /></span><div><h2 className="font-black text-slate-950">Privacy & security</h2><p className="mt-1 text-sm leading-6 text-slate-600">Your email is private. We use account information only to run and keep the service safe.</p></div></div></section></div></div>;
}
